plugins {
    id 'java'
    id("xyz.jpenilla.run-paper") version "3.0.2"
    id 'java-library'
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.22"
    id("com.gradleup.shadow") version "8.3.6"
}

group = 'me.tortel'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
//    maven {
//        url = uri('https://repo.aikar.co/content/groups/aikar/')
//    }
    maven {
        url = uri('https://oss.sonatype.org/content/groups/public/')
    }
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.48'
    annotationProcessor 'org.projectlombok:lombok:1.18.48'

    //compileOnly("io.papermc.paper:paper-api:26.2.build.+")

    //implementation "co.aikar:acf-paper:0.5.1-SNAPSHOT"

    paperweight.paperDevBundle("26.2.build.+")
}

tasks {
    runServer {
        // Configure the Minecraft version for our task.
        // This is the only required configuration besides applying the plugin.
        // Your plugin's jar (or shadowJar if present) will be used automatically.
        minecraftVersion("26.2")
    }

    // ADD THIS — makes shadowJar the default build output
    assemble {
        dependsOn(reobfJar)
    }

    shadowJar {
        manifest {
            attributes["paperweight-mappings-namespace"] = "mojang"
        }
    }

//    reobfJar {
//        inputJar.set(shadowJar.archiveFile)
//    }
    reobfJar {
        enabled = false
    }
}

def targetJavaVersion = 25
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
